version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - ./site/db:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: cc861010/recognize:latest
    ports:
      - '80:8181'
      - '443:8443'
    volumes:
      # - '/home/bear/projects/artisreit_wordpress/site/wwwroot/wordpress:/bitnami/wordpress'
      - '/home/bear/projects/artisreit_wordpress/site/conf:/opt/bitnami/nginx/conf'
      - '/home/bear/projects/artisreit_wordpress/site/nginx-cache:/var/run/nginx-cache'
      - '/home/bear/projects/artisreit_wordpress/site/log:/var/log/'
      - '/home/bear/projects/artisreit_wordpress/site/wwwroot:/var/www/'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - WORDPRESS_USERNAME=root
      - WORDPRESS_PASSWORD=root
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=root
      - WORDPRESS_DATABASE_PASSWORD=root
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
