version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
      - ./site/db:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_ROOT_USER=root
      - MARIADB_PASSWORD=root
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    image: artisreit/artisreit_wordpress:latest
    ports:
      - '80:8181'
      - '443:8443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - './site/conf:/opt/bitnami/nginx/conf'
      - './site/nginx-cache:/var/run/nginx-cache'
      - './site/log:/var/log/'
      - './site/wwwroot:/var/www/'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
